version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry==1.4.0
      - poetry config virtualenvs.create false
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html
