build:
  jobs:
    post_install:
      - pip install poetry==1.5.1
      - poetry config virtualenvs.create false
      - poetry install --with docs
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

version: 2
