version: 2
formats: []

build:
  image: testing
  tools:
    python: 3.9

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
