build:
  jobs:
    post_create_environment:
      - pip install -U poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --without speedups
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

version: 2
