build:
  jobs:
    post_create_environment:
      - pip install -U pdm
    post_install:
      - pdm config python.use_venv true
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install -dG docs
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

version: 2
